### ISSUE TITLE
IndieEffects.js throws syntax errors

### ISSUE THREAD

**Issue by Enemby** [GreatArcStudios/UnityIndieEffects#7]
I made a fix for the issue, mentioned here 
forum.unity3d.com/threads/indieeffects-bringing-almost-aaa-quality-post-process-fx-to-unity-indie.198568/page-26
since the github repo hasn't been updated with that fix yet.
My fix:
https://github.com/Enemby/UnityIndieEffects/blob/master/Indie%20Effects%20Git/Assets/IndieEffects/JS%20Classes/IndieEffects.js

**Comment by GreatArcStudios** [comment]
Sorry for not seeing this earlier, but if you still wish to update it just submit a pull request.
